@ECHO OFF
composer require drupal/config_update
composer require drupal/csv_serialization
composer require drupal/ctools
composer require drupal/devel
composer require drupal/diff
composer require drupal/easy_breadcrumb
composer require drupal/editor_advanced_link
composer require drupal/editor_file
composer require drupal/embed
composer require drupal/entity_clone
composer require drupal/entity_reference_revisions
composer require drupal/eu_cookie_compliance
composer require drupal/exclude_node_title
composer require drupal/extlink
composer require drupal/field_defaults
composer require drupal/field_permissions
composer require drupal/file_mdm
composer require drupal/geofield
composer require drupal/google_analytics
composer require drupal/google_tag
composer require drupal/honeypot
composer require drupal/image_effects
composer require drupal/linkit
composer require drupal/mailsystem
composer require drupal/masquerade
composer require drupal/menu_block
composer require drupal/metatag
composer require drupal/migrate_plus
composer require drupal/migrate_tools
composer require drupal/node_revision_delete
composer require drupal/paragraphs
composer require drupal/password_policy
composer require drupal/pathauto
composer require drupal/podcast
composer require drupal/poll
composer require drupal/quicklink
composer require drupal/redirect
composer require drupal/redis
composer require drupal/restui
composer require drupal/scheduler
composer require drupal/search_api
composer require drupal/search404
composer require drupal/shield
composer require drupal/simple_gmap
composer require drupal/simple_sitemap
composer require drupal/sitemap
composer require drupal/superfish
composer require drupal/token
composer require drupal/url_embed
composer require drupal/video
composer require drupal/video_embed_field
composer require drupal/view_unpublished
composer require drupal/views_accordion
composer require drupal/views_data_export
composer require drupal/views_infinite_scroll
composer require drupal/views_slideshow
composer require drupal/viewsreference
composer require drupal/webform
composer require drupal/weight
composer require drupal/yoast_seo
PAUSE